import "./globals.css";
import { Roboto, Parisienne, PT_Serif  } from 'next/font/google';

const roboto_init = Roboto({
    subsets: ['latin'],
    weight: ['300', '500', '700'],
    variable: '--font-roboto'
})

const parisienne_init = Parisienne({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-parisienne'
})

const pt_sarief_init = PT_Serif({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-pt_sarief'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto_init.variable} ${pt_sarief_init.variable} ${parisienne_init.variable}`}>{children}</body>
    </html>
  );
}
